version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - ecoai-net

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - ai-service
    networks:
      - ecoai-net

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./ai-service/data:/app/data  # Persist FAISS index
    networks:
      - ecoai-net

networks:
  ecoai-net:
    driver: bridge